version: "2.1"
services:
  webgrabplus:
    image: ghcr.io/linuxserver/webgrabplus:version-V3.2.2
    container_name: webgrabplus
    mac_address: 02:42:ac:11:65:43
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Bangkok
    volumes:
      - ./config:/config
      - ./data:/data
    restart: unless-stopped
